spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hls_train?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: admin
  redis:
    host: 127.0.0.1
    port: 6379
    database: 8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 80
logging:
  level:
    com.hand.hls.train.springbootdemoday01.mapper: debug